TERMINATION_PARM = 1e-4
OPT_GAP_PWL = 1e-4
OPT_GAP = 0.01
MAX_ITER_NUM = 300
MAX_ITER_NUM_HGNA = 100
LOCAL_SOL_NUM = 20
LOCAL_SOL_NUM_ID = 5
TIME_LIMIT = 14400
STABILITY_TYPE = 'cv'
STABILITY_THRESHOLD = 0.0
STABLE_FINDING_ITER = 5

SOLVER = 'GRB'

ID_LOCAL_APPROACH = 'SLP'

BOUND_VALUE_TYPE = 'APPROX'
EPS = 1e-3
SYSTEM_TIME_UNIT = 1
