TERMINATION_PARM = 1e-4
OPT_GAP_PWL = 1e-4
OPT_GAP = 0.01
MAX_ITER_NUM = 300
MAX_ITER_NUM_HGNA = 300
LOCAL_SOL_NUM = 50
LOCAL_SOL_NUM_ID = 50
TIME_LIMIT = 3600
STABILITY_TYPE = 'cv'
STABILITY_THRESHOLD = 0.0
STABLE_FINDING_ITER = 5

SOLVER = 'GRB'

ID_LOCAL_APPROACH = 'SLP'

BOUND_VALUE_TYPE = 'APPROX'
EPS = 1e-3
SYSTEM_TIME_UNIT = 1

CPU_PROCESS_TYPE_ID = 'PARALLEL'
TREE_BASE_ALGO_ID = 'DP'
MAX_DECOMPOSE_NUM_ID = 5
